<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="oav_V1">

    <xacro:arg name="prefix" default="rNESH"/>
    <xacro:property name="PREFIX" value="$(arg prefix)"/>
    
    <xacro:include filename="$(find oav_description)/urdf/components.urdf.xacro" />
    <xacro:include filename="$(find oav_description)/urdf/definations.urdf.xacro" />


    <xacro:base prefix="${PREFIX}"/>
    <xacro:neshLid_v1 prefix="${PREFIX}" parrent="base_link" x="0" y="0" z="${base_link_h/2}"/>

    <xacro:wheel prefix="${PREFIX}" location_prefix="right"/>
    <xacro:wheel prefix="${PREFIX}" location_prefix="left"/>


    <xacro:caster_wheel prefix="${PREFIX}" r_location_prefix="right" d_location_prefix="front"/>
    <xacro:caster_wheel prefix="${PREFIX}" r_location_prefix="left" d_location_prefix="front"/>


    <xacro:caster_wheel prefix="${PREFIX}" r_location_prefix="right" d_location_prefix="back"/>
    <xacro:caster_wheel prefix="${PREFIX}" r_location_prefix="left" d_location_prefix="back"/>
    

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
            <robotNamespace></robotNamespace>
            <robotParam>robot_description</robotParam>
            <controlPeriod>0.002</controlPeriod>
        </plugin>
    </gazebo>


</robot>